name: Build/Compile
on:
  push:
    branches: [ "main" ]
    paths: ['markdown/**']
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Compile
        run: python3 utils/compile.py

      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --global user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add static/articles/ index.html
          git commit -m "updated pages"
          git push
